# Generated by Django 6.0.2 on 2026-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=10),
        ),
    ]
