# Generated by Django 6.0.2 on 2026-02-17 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, height_field='100px', null=True, upload_to='company_logo/', width_field='100px')),
                ('company_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('company_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=50)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('200+', '200+ Employees')], max_length=50)),
                ('created_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employer')),
            ],
        ),
    ]
