# Generated by Django 6.0.2 on 2026-02-20 03:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_employer_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='application_deadline',
            field=models.DateField(default=datetime.datetime(2026, 2, 20, 3, 12, 41, 981635, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='jobs',
            name='application_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='application_method',
            field=models.CharField(choices=[('platform', 'Apply on Platform'), ('external', 'External Link')], default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.employer'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='experience_required',
            field=models.CharField(blank=True, choices=[('fresher', 'Freshers'), ('1-2', '1-2 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='opening',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobs',
            name='responsibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.CharField(blank=True, help_text='Enter skills seperated by commas', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('onsite', 'onsite'), ('remote', 'remote'), ('hybrid', 'hybrid')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_job', to='jobs.employer'),
        ),
    ]
