# Generated by Django 6.0.2 on 2026-02-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobs_salary_alter_jobs_application_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default='draft'),
        ),
    ]
