# Generated by Django 6.0.2 on 2026-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobs_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(choices=[('active', 'Active'), ('closed', 'closed'), ('draft', 'Draft'), ('published', 'Published')], default='draft'),
        ),
    ]
