# Generated by Django 6.0.2 on 2026-02-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobs_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Closed', 'Closed'), ('Active', 'Active')], default='Draft', max_length=50),
        ),
    ]
