# Generated by Django 6.0.2 on 2026-02-27 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobs_is_active_alter_jobs_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('skills', models.TextField()),
                ('profesional_summary', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('highest_qualification', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
