# Generated by Django 6.0.2 on 2026-03-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_application_name_application_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
