# Generated by Django 6.0.2 on 2026-03-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Interview_Scheduled', 'Interview_Scheduled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
