# Generated by Django 6.0.2 on 2026-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_jobs_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='skills',
            field=models.CharField(blank=True, help_text='Enter skills seperated by commas', max_length=250, null=True),
        ),
    ]
