# Generated by Django 6.0.2 on 2026-04-14 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_jobs_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^\\d{10}$')]),
        ),
    ]
