# Generated by Django 6.0.2 on 2026-04-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(default='', upload_to='resume/'),
            preserve_default=False,
        ),
    ]
