# Generated by Django 6.0.2 on 2026-04-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_employee_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
