# Generated by Django 6.0.2 on 2026-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(default='', upload_to='company_logo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
